package(default_visibility = ["//visibility:public"])

java_library(
    name = "net",
    srcs = ["NetUtil.java"],
    deps = [
        "//:lombok",
        "@http_client_maven//:compile",
    ],
)

java_library(
    name = "ratelimiter",
    srcs = ["RateLimiter.java"],
    deps = [
        "//:lombok",
    ],
)

java_library(
    name = "time",
    srcs = ["TimeUtil.java"],
    deps = [
        "//:lombok",
    ],
)
